import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import Navbar from './components/Header/Navbar';

// const inter = Space_Grotesk({ subsets: ['latin'] });

export const metadata = {
  title: 'Hello JVM!',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
